version: '3.1'

volumes:
  postgres_vol:

networks:
  pgadmin_rede:
    driver: bridge

services:
  postgres:
    image: postgres:14.5
    networks:
      - pgadmin_rede
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgres
    environment:
      POSTGRES_USER: ff@ff.com
      POSTGRES_PASSWORD: postgres_
      POSTGRES_DB: db_2

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - pgadmin_rede
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ff@ff.com
      PGADMIN_DEFAULT_PASSWORD: postgres_
    


